name: 'Trivy Security Scan'
description: 'Perform a security scan on a Docker image using Trivy.'
inputs:
  image-name:
    description: 'Docker image to scan'
    required: true
  severity-level:
    description: 'Severity level of vulnerabilities to detect'
    required: false
    default: 'HIGH,CRITICAL'
  docker-hub-username: 
    description: 'Username of the Docker Hub.'
    required: true
  docker-hub-token: 
    description: 'Access tokan of the Docker Hub.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) stable | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
      shell: bash

    - name: Login to Docker Hub
      uses: ./.github/actions/docker-login
      with:
        docker-hub-username: ${{ inputs.docker-hub-username }}
        docker-hub-token: ${{ inputs.docker-hub-token }}

    - name: Pull Docker image
      run: docker pull ${{ inputs.image-name }}:latest
      shell: bash

    - name: Run Trivy Scan
      run: trivy image --severity ${{ inputs.severity-level }} ${{ inputs.image-name }}
      shell: bash