name: 'Docker Hub Login'
description: 'Perform a valid login to Docker Hub'

env:
  docker_image_name: szikoramarci/face-recognition

runs:
  using: "composite"
  steps:
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    password: ${{ secrets.DOCKER_HUB_TOKEN }} 