name: 'Docker Hub Login'
description: 'Perform a valid login to Docker Hub'
inputs:
  docker-hub-username: 
    description: 'Username of the Docker Hub.'
    required: true
  docker-hub-token: 
    description: 'Access tokan of the Docker Hub.'
    required: true

runs:
  using: "composite"
  steps:
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.docker-hub-username }}
      password: ${{ inputs.docker-hub-token }}