name: 'Python Test'
description: 'Sets up Python, installs dependencies, lints, and runs tests.'
inputs:
  python-version:
    description: 'Version of the python'
    required: true

runs:
  using: "composite"
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Lint with flake8
      run: flake8 src
      shell: bash

    - name: Run tests with pytest
      run: pytest
      shell: bash