name: 'Docker Build and Push'
description: 'Builds a Docker image and pushes it to Docker Hub.'
inputs:
  image-name:
    description: 'Name of the Docker image to build and push.'
    required: true
  docker-hub-username: 
    description: 'Username of the Docker Hub.'
    required: true
  docker-hub-token: 
    description: 'Access tokan of the Docker Hub.'
    required: true


runs:
  using: "composite"
  steps: 
  - name: Build Docker image
    run: docker build -t ${{ inputs.image-name }}:latest .
    shell: bash

  - name: Login to Docker Hub
    uses: ./.github/actions/docker-login
    with:
      docker-hub-username: ${{ inputs.docker-hub-username }}
      docker-hub-token: ${{ inputs.docker-hub-token }}

  - name: Push Docker image
    run: docker push ${{ inputs.image-name }}:latest
    shell: bash