name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  docker_image_name: szikoramarci/face-recognition

jobs:
  test:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 src

    - name: Run tests with pytest
      run: pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t $docker_image_name:latest .
      shell: bash

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Push Docker image
      run: docker push $docker_image_name:latest
        
  security-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Pull Docker image
      run: docker pull $docker_image_name:latest

    - name: Set up Trivy
      run: |
        sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) stable | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update && sudo apt-get install -y trivy

    - name: Run Trivy vulnerability scanner and generate HTML report
      run: trivy image --format template --template "@contrib/html.tpl" --output trivy-report.html $docker_image_name:latest

    - name: Upload Trivy Report as an Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Trivy HTML Report
        path: trivy-report.html

    - name: Run Trivy Scan
      run: trivy image --severityHIGH,CRITICAL $docker_image_name:latest
       