name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  docker_image_name: szikoramarci/face-recognition

jobs:
  test:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Testing Action
      uses: ./.github/actions/python-test
      with:
        python-version: ${{ matrix.python-version }}

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Run Building And Pushing Action
      uses: ./.github/actions/build-and-push
      with:
        image-name: $docker_image_name
        
  security-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps: 
    - name: Run Security Scan Action
      uses: ./.github/actions/security-scan
      with:
          image-name: $docker_image_name